# Generated by Django 5.2.8 on 2025-11-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_slug_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=70), null=True),
        ),
    ]
