# Generated by Django 5.2.8 on 2025-11-26 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 16, 5, 51, 260826, tzinfo=datetime.timezone.utc)),
        ),
    ]
