# Generated by Django 5.2.8 on 2025-11-28 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_message_age_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 28, 15, 15, 53, 763879, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 28, 15, 15, 53, 763879, tzinfo=datetime.timezone.utc)),
        ),
    ]
